name: Code Formatter & Update Leaderboard
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Code Formatter & Update Leaderboard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: "."

      - name: Install dependencies and Update Leaderboard
        run: |
          python -m pip install pytz
          python -m pip install wordsegment
          python top.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v2.1.0
        with:
          author_name: asdf2014
          author_email: asdf2014@apache.org
          message: "Code Formatter & Update Leaderboard"
          path: "Codes README.md README-en.md .idea/dictionaries/yuzhouwan.xml"
          pattern: "*.*"
          force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
